backend:
  name: github
  repo: wakatobi-update/wakatobi-update.github.io
  branch: main
  client_id: 0v23livfAnI4r20dB9h8

media_folder: "Ai/images"
public_folder: "/Ai/images"

collections:
  - name: "news"
    label: "Berita"
    folder: "Ai/news"
    create: true
    slug: "{{slug}}"

    fields:
      - { label: "Judul", name: "title", widget: "string" }
      - { label: "Tanggal", name: "date", widget: "datetime" }
      - { label: "Isi", name: "body", widget: "markdown" }
