backend:
  name: github
  repo: wakatobi-update/wakatobi-update.github.io
  branch: main

media_folder: "Ai/images"
public_folder: "/Ai/images"

collections:
  - name: "news"
    label: "Berita"
    folder: "Ai/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"

    fields:
      - { label: "Judul", name: "title", widget: "string" }
      - { label: "Tanggal", name: "date", widget: "datetime" }
      - { label: "Kategori", name: "category", widget: "string" }
      - { label: "Gambar", name: "image", widget: "image" }
      - { label: "Isi Berita", name: "body", widget: "markdown" }
