backend:
  name: github
  repo: wakatobi-update/wakatobi-update.github.io
  branch: main
  client_id: 0v23livfAnI4r20dB9h8

media_folder: "gallery"
public_folder: "/gallery"

collections:
  - name: "berita"
    label: "Berita"
    folder: "news"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Judul", name: "title", widget: "string"}
      - {label: "Isi Berita", name: "content", widget: "text"}
      - {label: "Tanggal", name: "date", widget: "datetime"}
      - {label: "Gambar", name: "image", widget: "image"}
